### ISSUE TITLE
Git branch only resolved if lilly is launched from the base dir

### ISSUE THREAD

**Issue by valxntine** [tauraamui/lilly#111]
If lilly is opened from anywhere other than the base directory of the project (where the `.git` file is found) then the git branch isn't resolved.

The issue is in `./src/lib/workspace/workspace.v` in the `resolve_git_branch_name` function, `is_dir` is called just on the workspace directory checking for `.git`

We can walk back up directories until we find `.git`, but there has to be a limit.

**Comment by tauraamui** [comment]
@valxntine  has a fix but he's holding out on us.
