### ISSUE TITLE
Use ropes instead of array of (lines of) characters to prevent choking on large files (JSONs, etc.)

### ISSUE THREAD

**Issue by dumblob** [tauraamui/lilly#128]
See title :wink:.

**Comment by tauraamui** [comment]
I agree, for larger files (not yet decided on the appropriate cut off/size to switch on yet) we will use ropes instead of an array. Neovim uses a linked list, I considered this but it seems like the worse of the three options to be honest.

**Comment by tauraamui** [comment]
This approach (of using ropes) has been shelved in favour of switching to use a gap buffer as our backing data structure for everything for now.
