### ISSUE TITLE
User friendly way to start the application 

### ISSUE THREAD

**Issue by hholst80** [tauraamui/lilly#148]
Why does lilly not allow me to start it like a normal application?

When I start the application I get this error:

```
# ./lilly
too many file paths, expected just one
```

I expect to be able to start the editor like any normal TUI application.

https://www.youtube.com/shorts/EvRKLO3TcOg

**Comment by tauraamui** [comment]
It does, try `./lilly .` which will tell it to open with the current PWD. :)

**Comment by tauraamui** [comment]
Having said that, the error message is poor, apologies. I will add some basic documentation hopefully soon, and also improve the error messaging. Thank you for your input!

**Comment by hholst80** [comment]
Perhaps. I have found that the "v ." Build pattern works well for me. Perhaps we can still wrap around that? If there is a need for a build system sure let's not reinvent the wheel but use what we should.

My Primary concern was however on how the application is launched after the Binary has been built. There should be no external dependencies to launch it after the Build has taken place. Reasonable?

**Comment by tauraamui** [comment]
There technically aren't, you can run the compiled build directly, but you *must* provide a single path as the first argument, at least for now. I'm personally just running it with `./lilly .`. Does this make sense?

**Comment by tauraamui** [comment]
I've addressed the issue with using an alternative/uncommon build system, now anyone with the ability to execute bash scripts can run all the necessary tool commands, changed in #150.

**Comment by hholst80** [comment]
Thank you! I first opened the issue on my mobile so I did not see the first comments you made on the launcher, my apologies for that.  :-)

**Comment by tauraamui** [comment]
No apology needed, but thank you! I assumed you missed it somehow and so just decided to repeat it again 😂. Anyway, I'll leave this issue open until I've improved the error messaging for the case you originally demonstrated.

**Comment by hholst80** [comment]
I actually get a SIGSEGV now.  V version 0.4.5 2e64e28

**Comment by tauraamui** [comment]
> I actually get a SIGSEGV now. V version 0.4.5 2e64e28
> 
> To be clear it withs with `./just.sh` but if I run the `./lilly .` it crashes.
> 
> ```
> [I] root@trump ~/lilly (master) 
> # ./just.sh
> git log -n 1 --pretty=format:"%h" | tee ./src/.githash
> 75af77cv -g run ./src .
> [I] root@trump ~/lilly (master) 
> # ./lilly .
> [I] root@trump ~/lilly (master) [SIGSEGV] 
> # 
> ```

That's strange, I'll get back to you with more questions.

**Comment by tauraamui** [comment]
In the same directory as the lilly bin there should be a `lilly.panic.log` file, could you please attach the contents of it here?

**Comment by tauraamui** [comment]
Is there any update on providing the panic stack trace?

**Comment by tauraamui** [comment]
I have been able to re-produce Lilly inexplicably crashing for no known nor recorded (in the panic dump nor debug) reason on Xubuntu. I will need to test further to identify what is happening but for now I am closing this issue (mostly because it's gotten off topic from the original comments which have been addressed).
