### ISSUE TITLE
Build system

### ISSUE THREAD

**Issue by Eliyaan** [tauraamui/lilly#149]
What is the best build solution? Because not everyone has `just`. But it seems nice too.

**Comment by tauraamui** [comment]
So historically I've always defaulted to using Make, but I have found `just` to be nicer. However it is true that most people likely do not have `just` installed, whereas it's almost certain that they do have Make. I suppose the most ideal solution would be to have both a `justfile` and a `Makefile` with equivalent "steps" or "recipes", but keeping these in sync would be a challenge. I am unsure what to do as of yet, perhaps the solution might be to incorporate a step in our test run which ensures equivalent contents of both files somehow? Or using a `bash` script? Or maybe even a very easy to run custom "build tool" for this project? As I say, I am unsure.

**Comment by tauraamui** [comment]
Resolved with #150 . Thanks! :)
