### ISSUE TITLE
Assist with "How do I quit Lilly"

### ISSUE THREAD

**Issue by hholst80** [tauraamui/lilly#155]
I think it would be great if there was a `<leader>qq` to quit Lilly.  It should also be part of the menu listing at start so people see it.

![image](https://github.com/tauraamui/lilly/assets/6200749/53ec8ab4-7c05-467c-ade3-072297ee19ef)

**Comment by tauraamui** [comment]
This is a good idea. Either raise a PR or I can follow up with this change at a later date.

**Comment by tauraamui** [comment]
Fixed with #170
