### ISSUE TITLE
compile-gui not building on linux now

### ISSUE THREAD

**Issue by wilsonk** [tauraamui/lilly#200]
Getting this error (plus a few more related to this line:
```
src/main.v:200:11: error: assignment mismatch: 2 variables but `src.lib.draw.new_context()` returns 1 value
  198 |     }
  199 | 
  200 |     ctx, run := draw.new_context(
      |              ~~
  201 |         user_data:            app
  202 |         event_fn:             event

```
That is will 'v up' from Sept 21, 2024, so maybe something changed there?

**Comment by wilsonk** [comment]
It looks like this error is probably due to this push Fix/improve file finder perf (https://github.com/tauraamui/lilly/pull/194). 

I modified gui_d_gui.v according to the changes in that fix, and 'compile-gui' builds, but it doesn't seem to run properly. Nothing appears in the window and input doesn't seem to work.

Any ideas on this one?

**Comment by tauraamui** [comment]
Interesting, basically no I don't know what is going on here, I'll need to investigate.

**Comment by wilsonk** [comment]
This same error happens on windows also. Hopefully this can get fixed soon (by myself or others :) ) so that I can test the gui on windows. Unfortunately, I don't quite understand why this error is happening or how to fix it :(

**Comment by wilsonk** [comment]
This compiles now, but there is a problem with displaying the splash screen now (no text is shown in the opened window and input doesn't seem to work)...I will leave this open for now, but maybe we should close this one and open a new issue?

**Comment by tauraamui** [comment]
I agree, seeing as this issue is specifically related to compilation failure and that's been inexplicably resolved on both Linux (and Windows?) issues related to rendering within the GUI mode should have it's own dedicated issue.
