### ISSUE TITLE
bug: src/.githash is required to build code, but is .gitignored

### ISSUE THREAD

**Issue by Kaamkiya** [tauraamui/lilly#251]
Building code with `v .` requires lilly to embed `src/.githash`, but in the `.gitignore` (line 31), `src/.githash` is ignored.

**Comment by tauraamui** [comment]
Yes, because its generated every time you execute `clockwork run` or `clockwork build`, its only there to tell you locally which commit your build is based on.

**Comment by Kaamkiya** [comment]
Ohhh, I didn't use clockwork to build. I guess that explains it.
