### ISSUE TITLE
W + E should handle non-alpha chars differently

### ISSUE THREAD

**Issue by tauraamui** [tauraamui/lilly#39]

**Comment by BKR-dev** [comment]
https://github.com/tauraamui/lilly/tree/fix/MoveWordForward

val and i did some big brain coding and im going to continue it on my own (very scary)

**Comment by BKR-dev** [comment]
this would still fail on `))))` or `},}` which is needed to make it stable

**Comment by BKR-dev** [comment]
i cannot believe i didnt work on this for 3 WEEKS what the heck dude....

**Comment by BKR-dev** [comment]
after some looking and testing it seems good to me, handles multiple closing brackets
