### ISSUE TITLE
Implement "a" and "A" commands

### ISSUE THREAD

**Issue by valxntine** [tauraamui/lilly#43]
A core keybinding in vim is the `a` and `A` commands, for appending from the current cursor position and appending at the end of the current line.

This work should also include tests reflecting the functionality of both functions of the `a` key.

**Comment by tauraamui** [comment]
@valxntine we should be able to take advantage of this from the V stdlib when the time comes: https://modules.vlang.io/strings.html#find_between_pair_u8
