### ISSUE TITLE
cmd buffer output not being cleared

### ISSUE THREAD

**Issue by valxntine** [tauraamui/lilly#95]
When you exec a command, `:w` for example, you get a message to tell you if its been successful or not, or not recognised. 

This message persists even when using the space in the UI, for example performing a search:
![image](https://github.com/tauraamui/lilly/assets/24855366/cec79a99-cda9-4a86-ad35-b66f383e8453)

**Comment by wilsonk** [comment]
I think this can be closed after commit e3f8cb0, yes?

**Comment by tauraamui** [comment]
> I think this can be closed after commit [e3f8cb0](https://github.com/tauraamui/lilly/commit/e3f8cb08718aefba19efc73cf6a2e95580b65421), yes?

Yeah.
